name: check-code-quality
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

	steps:
	- uses: actions/checkout@v1

	- name: Set up Python 3.8
	  uses: actions/setup-python@v1
	  with:
	    python-version: 3.8

    - name: GitHub Action for pylint
	  uses: cclaus/GitHub-Action-for-pylint@0.7.0

